// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/routes/[...]').default>>>>
    }
    '/export': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/routes/export').default>>>>
    }
    '/health': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/routes/health').default>>>>
    }
    '/public/resume': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/routes/public/resume').default>>>>
    }
    '/resumes': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/routes/resumes').default>>>>
    }
  }
}
export {}